[package]
name = "yarp_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
petgraph = {version = "0.8.1", features=["std"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
